name: 'Autotag'
author: 'phish108'
description: 'Autotag with Semantic Versioning and Issue integration'
branding:
  icon: tag
  color: blue
inputs:
  github-token:  # id of input
    default: ${{ github.token }}
    required: false # not required, so default can do its magic
    description: 'the GH token to connect to github from the action'
  dry-run: 
    description: "check if the action would succeed"
    required: false
    default: "FALSE"
  force:
    description: "force tagging even if the tag already exists"
    required: false
    default: "FALSE"
  bump: 
    description: "which part of the semver needs to be updated?"
    required: false
    default: "patch"
  branch: 
    description: "force to tag a specific branch"
    required: false
    default: ""
  version-prefix: 
    description: "the version prefix to use. This does not imply with-v!"
    required: false
    default: "v"
  with-v: 
    description: "tag with version prefix. uses the prefix provided by version-prefix."
    required: false
    default: "FALSE"
  style: 
    description: "versioning style"
    required: false
    default: "semver"
  tag: 
    description: "use custom tag"
    required: false
    default: ""
  release-branch: 
    description: "provide the names from which branches to release"
    required: false
    default: "main,master"
  issue-labels:
    description: "provide a comma separated list of labels that trigger a minor version bump"
    required: false
    default: "enhancement"
outputs:
  new-tag: # id of output
    description: 'new tag'
  tag: # id of output
    description: 'latest tag'
runs:
  using: 'node12'
  main: 'dist/index.js'
